name: Daily Manus Digest to HTML

on:
  schedule:
    - cron: '0 22 * * *'  # 5:00 PM Eastern during Standard Time (UTC-5)
    - cron: '0 21 * * *'  # 5:00 PM Eastern during Daylight Time (UTC-4)
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch-and-store:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set today's date env
        run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Ensure tools and directories
        run: |
          sudo apt-get update -y
          sudo apt-get install -y jq
          mkdir -p posts

      - name: Fetch latest Manus output and save to file (with retries)
        env:
          MANUS_API_KEY: ${{ secrets.MANUS_API_KEY }}
        run: |
          set -euo pipefail

          retry() {
            # args: <method> <url> [data]
            local method="$1"; shift
            local url="$1"; shift
            local data="${1:-}"

            for attempt in {1..6}; do
              echo "Attempt $attempt: $method $url"
              if [ -n "$data" ]; then
                RESP=$(curl -sS -D /tmp/headers.txt -o /tmp/body.txt \
                  -H "Authorization: Bearer $MANUS_API_KEY" \
                  -H "Accept: application/json" \
                  -X "$method" "$url" --data "$data" -w "%{http_code}")
              else
                RESP=$(curl -sS -D /tmp/headers.txt -o /tmp/body.txt \
                  -H "Authorization: Bearer $MANUS_API_KEY" \
                  -H "Accept: application/json" \
                  -X "$method" "$url" -w "%{http_code}")
              fi

              CODE="$RESP"
              echo "HTTP $CODE"
              head -c 400 /tmp/body.txt || true
              echo

              if [ "$CODE" = "200" ]; then
                return 0
              fi

              if [ "$CODE" = "429" ] || [[ "$CODE" =~ ^5 ]]; then
                SLEEP=$(awk -F': ' 'tolower($1)=="retry-after"{print $2}' /tmp/headers.txt | tr -d '\r' || true)
                SLEEP=${SLEEP:-$((2 ** attempt))}
                echo "Rate limited/server error. Sleeping ${SLEEP}s…"
                sleep "$SLEEP"
                continue
              fi

              echo "Unexpected HTTP status: $CODE"
              cat /tmp/body.txt || true
              return 1
            done

            echo "Gave up after retries."
            cat /tmp/body.txt || true
            return 1
          }

          TODAY=${TODAY:-"$(date +'%Y-%m-%d')"}
          mkdir -p posts

          # 1) Get the most recent output (adjust query params if you want to scope further)
          retry GET "https://api.manus.ai/v1/outputs?limit=1"

          OUTPUT_ID=$(jq -r '.data[0].id // empty' < /tmp/body.txt)
          if [ -z "$OUTPUT_ID" ]; then
            echo "No outputs returned by Manus API."
            echo "Full body:"; cat /tmp/body.txt || true
            exit 1
          fi
          echo "Latest OUTPUT_ID: $OUTPUT_ID"

          # 2) Download that output as HTML
          retry GET "https://api.manus.ai/v1/outputs/$OUTPUT_ID"

          cp /tmp/body.txt "posts/${TODAY}-ai-digest.html"

          # 3) Sanity check
          if [ ! -s "posts/${TODAY}-ai-digest.html" ]; then
            echo "Downloaded file is empty."
            exit 1
          fi

      - name: Update archive.html
        run: |
          LINE="<li><a href='posts/${TODAY}-ai-digest.html'>${TODAY}</a></li>"
          touch archive.html
          grep -qxF "$LINE" archive.html || echo "$LINE" >> archive.html

      - name: Commit and push
        run: |
          git config --global user.name 'AI Digest Bot'
          git config --global user.email 'aibot@example.com'
          git add "posts/${TODAY}-ai-digest.html" archive.html
          git commit -m "📥 Add AI Digest for ${TODAY}" || echo "No changes to commit"
          git push
